### ISSUE TITLE
Crash when use function e as usage.

### ISSUE THREAD

**Issue by moyotar** [davidshepherd7/emacs-read-stdin#1]
![image](https://user-images.githubusercontent.com/22092607/33200456-af455b8e-d12f-11e7-945d-1df0369d3fab.png)
I've copy this two function into my `.bashrc`. But I get failure when using.

**Comment by davidshepherd7** [comment]
What's the error message?

**Comment by moyotar** [comment]
Get nothing about error and it just return to shell with a new emacs frame flashing back.

**Comment by davidshepherd7** [comment]
Some other ideas:

* Is there anything in the `*Messages*` buffer?
* What's the command you're running? Is it just `e`?
* Does `emacsclient -c -n some/file/path` work ok? Maybe try some of the other commands too.

**Comment by moyotar** [comment]
For both of `e` and `emacsclient -c -n some/file/path`， It just flash back to shell and cause a error message `Invalid face reference: linum [4 times]` in `*Messages*`.

**Comment by moyotar** [comment]
@davidshepherd7 If I remove the `-n` option, the command `e file` works but another one still fails.

**Comment by davidshepherd7** [comment]
It sounds like a problem with your emacs setup rather than the script. I don't really have any ideas for figuring out what's wrong other than the usual: run with `-Q` and if it works then try commenting out chunks until you find the problem. Or the more sophisticated version of this: https://github.com/Malabarba/elisp-bug-hunter 

Sorry I can't help more...

**Comment by davidshepherd7** [comment]
Oh I guess you could also check if using `emacs` instead of `emacsclient` works

**Comment by moyotar** [comment]
@davidshepherd7 I found the reason for that. In function `_emacsfun`, the arg `$@` should be `“$@”`.

**Comment by davidshepherd7** [comment]
Heh that's embarrassing, I guess I wrote this before I discovered shellcheck. Good spot, thanks.
